import { Request, Response } from "express";
import { z } from "zod";
import { formatZodError } from "../utils";
import { processEnrollmentMessage } from "../services/enrollmentAI";
import { storage } from "../storage";
import { getAuthEmail, getAuthUserId, AuthenticatedRequest } from "../utils/auth";
import { createEnrollmentDataSimple } from "@shared/enrollment-factory";

// Input validation schema
const messageSchema = z.object({
  message: z.string().min(1, "Message is required"),
  childrenIds: z.array(z.number()).optional(),
  history: z.array(z.object({
    role: z.enum(["system", "user", "assistant"]),
    content: z.string()
  })).optional()
});

/**
 * Calculate age from birthdate string
 */
function calculateAge(birthdate: string): number {
  const today = new Date();
  const birthDate = new Date(birthdate);
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDifference = today.getMonth() - birthDate.getMonth();
  
  if (monthDifference < 0 || (monthDifference === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  
  return age;
}

/**
 * Process a request from the enrollment assistant
 */
export const handleEnrollmentMessage = async (req: AuthenticatedRequest, res: Response) => {
  try {
    // Validate input
    const parseResult = messageSchema.safeParse(req.body);
    
    if (!parseResult.success) {
      return res.status(400).json({
        message: "Invalid request body",
        errors: formatZodError(parseResult.error)
      });
    }
    
    const { message, childrenIds = [], history = [] } = parseResult.data;
    
    // Check authentication - require at least email or user ID
    const parentEmail = getAuthEmail(req);
    const userId = getAuthUserId(req);
    
    if (!parentEmail && !userId) {
      console.log('❌ Authentication failed - no email or userId found');
      return res.status(401).json({ message: "You need to be logged in to use the enrollment assistant" });
    }
    
    // Use the service function that contains confirmation handling logic
    const response = await processEnrollmentMessage(
      message,
      childrenIds,
      history,
      parentEmail
    );
    
    // Execute any actions that were generated
    if (response.action) {
      try {
        console.log('🎯 About to execute enrollment action:', response.action);
        await executeEnrollmentAction(response.action, req);
        console.log('✅ Enrollment action executed successfully:', response.action);
      } catch (error) {
        console.error('❌ Failed to execute enrollment action:', error);
        console.error('❌ Error details:', error.message);
        // Still return the response but log the execution failure
      }
    } else {
      console.log('🔍 No action found in AI response');
    }
    
    return res.json(response);
  } catch (error) {
    console.error('Enrollment assistant error:', error);
    return res.status(500).json({ 
      message: "Something went wrong with the enrollment assistant. Please try again." 
    });
  }
};

/**
 * Execute an enrollment action generated by the AI
 */
async function executeEnrollmentAction(action: any, req: AuthenticatedRequest): Promise<void> {
  console.log('🎯 Executing enrollment action:', action);
  
  switch (action.type) {
    case 'enroll':
      if (action.childId && action.programId) {
        console.log(`📝 Creating enrollment for child ${action.childId} in program ${action.programId}`);
        
        // Get child and program details
        const child = await storage.getChildById(action.childId);
        const program = await storage.getClassById(action.programId);
        
        if (!child) {
          throw new Error(`Child with ID ${action.childId} not found`);
        }
        
        if (!program) {
          throw new Error(`Program with ID ${action.programId} not found`);
        }
        
        // Get parent information
        const parentEmail = getAuthEmail(req) || child.parentEmail || '';
        const parentId = child.parentId;
        
        // Determine pricing based on program and option
        let programPrice = program.price || 1300; // Default to $1300 for Tycoons Full Day
        
        // Override pricing for specific programs
        if (program.title === "Tycoons") {
          programPrice = 1300; // Full Day Including Afternoon Extracurriculars
        }
        
        // Use factory function to create complete enrollment data
        const enrollmentData = createEnrollmentDataSimple({
          schoolId: child.schoolId || program.schoolId || null,
          parentId,
          parentEmail,
          childId: action.childId,
          childName: `${child.firstName} ${child.lastName}`,
          classId: action.programId,
          className: program.title,
          classType: 'school_class',
          totalCost: programPrice,
          depositRequired: Math.round(programPrice * 0.1),
          remainingBalance: programPrice,
          paymentStatus: 'pending',
          programStartDate: program.startDate || new Date(),
          programEndDate: program.endDate || new Date()
        });
        
        const enrollment = await storage.createProgramEnrollment(enrollmentData);
        console.log('✅ Enrollment created:', enrollment);
      }
      break;
      
    case 'register_child':
      if (action.registrationData) {
        console.log('👶 Registering new child:', action.registrationData);
        
        const { name, age, grade, phone, address, emergency1, emergency2, medical, caregiver } = action.registrationData;
        
        // Split name into first and last
        const nameParts = name.split(' ');
        const firstName = nameParts[0] || 'Unknown';
        const lastName = nameParts.slice(1).join(' ') || 'Unknown';
        
        // Calculate birthdate from age
        const currentYear = new Date().getFullYear();
        const birthYear = currentYear - age;
        const birthdate = `${birthYear}-06-15`; // Use June 15 as default
        
        // For demo, use a test parent ID - in production this should come from auth
        const parentId = req.auth?.userId || 'demo-parent-123';
        
        const childData = {
          firstName,
          lastName,
          birthdate,
          gradeLevel: grade,
          parentId,
          interests: ['General Learning'],
          learningStyle: 'Visual',
          specialNeeds: medical === 'None' ? null : medical,
          medicalInfo: medical,
          emergencyContacts: [
            {
              name: emergency1 || 'Emergency Contact',
              phone: phone || '',
              relationship: 'Parent/Guardian'
            }
          ]
        };
        
        const child = await storage.createChild(childData);
        console.log('✅ Child registered:', child);
      }
      break;
      
    default:
      console.log('ℹ️ No action execution needed for type:', action.type);
  }
}

/**
 * Parse potential actions from the AI response
 */
function parseActionFromResponse(response: string): any {
  // This function is kept for compatibility but the main logic is now in the service
  return null;
}