import { Request, Response } from "express";
import { z } from "zod";
import { formatZodError } from "../utils";
import { processEnrollmentMessage } from "../services/enrollmentAI";
import { storage } from "../storage";

// Input validation schema
const messageSchema = z.object({
  message: z.string().min(1, "Message is required"),
  childrenIds: z.array(z.number()).optional(),
  history: z.array(z.object({
    role: z.enum(["system", "user", "assistant"]),
    content: z.string()
  })).optional()
});

/**
 * Calculate age from birthdate string
 */
function calculateAge(birthdate: string): number {
  const today = new Date();
  const birthDate = new Date(birthdate);
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDifference = today.getMonth() - birthDate.getMonth();
  
  if (monthDifference < 0 || (monthDifference === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  
  return age;
}

/**
 * Process a request from the enrollment assistant
 */
export const handleEnrollmentMessage = async (req: Request, res: Response) => {
  try {
    // Validate input
    const parseResult = messageSchema.safeParse(req.body);
    
    if (!parseResult.success) {
      return res.status(400).json({
        message: "Invalid request body",
        errors: formatZodError(parseResult.error)
      });
    }
    
    const { message, childrenIds = [], history = [] } = parseResult.data;
    
    // Check authentication - require at least email or user ID
    if (!req.auth?.email && !req.auth?.userId && !req.auth?.supabaseId) {
      console.log('❌ Authentication failed - req.auth:', req.auth);
      return res.status(401).json({ message: "You need to be logged in to use the enrollment assistant" });
    }

    // Get parent email for context (since children are linked by parent email)
    const parentEmail = req.auth?.email;
    
    // Use the service function that contains confirmation handling logic
    const response = await processEnrollmentMessage(
      message,
      childrenIds,
      history,
      parentEmail
    );
    
    // Execute any actions that were generated
    if (response.action) {
      try {
        await executeEnrollmentAction(response.action, req);
        console.log('✅ Enrollment action executed successfully:', response.action);
      } catch (error) {
        console.error('❌ Failed to execute enrollment action:', error);
        // Still return the response but log the execution failure
      }
    }
    
    return res.json(response);
  } catch (error) {
    console.error('Enrollment assistant error:', error);
    return res.status(500).json({ 
      message: "Something went wrong with the enrollment assistant. Please try again." 
    });
  }
};

/**
 * Execute an enrollment action generated by the AI
 */
async function executeEnrollmentAction(action: any, req: Request): Promise<void> {
  console.log('🎯 Executing enrollment action:', action);
  
  switch (action.type) {
    case 'enroll':
      if (action.childId && action.programId) {
        console.log(`📝 Creating enrollment for child ${action.childId} in program ${action.programId}`);
        
        // Get child and program details
        const child = await storage.getChildById(action.childId);
        const program = await storage.getClassById(action.programId);
        
        if (!child) {
          throw new Error(`Child with ID ${action.childId} not found`);
        }
        
        if (!program) {
          throw new Error(`Program with ID ${action.programId} not found`);
        }
        
        // Create the enrollment
        const enrollmentData = {
          classId: action.programId,
          childId: action.childId,
          childName: `${child.firstName} ${child.lastName}`,
          className: program.title,
          status: 'pending_payment' as const,
          enrollmentDate: new Date().toISOString(),
          amount: 0,
          depositRequired: Math.round(program.price * 0.1), // 10% deposit
          totalCost: program.price,
          remainingBalance: program.price
        };
        
        const enrollment = await storage.createEnrollment(enrollmentData);
        console.log('✅ Enrollment created:', enrollment);
      }
      break;
      
    case 'register_child':
      if (action.registrationData) {
        console.log('👶 Registering new child:', action.registrationData);
        
        const { name, age, grade, phone, address, emergency1, emergency2, medical, caregiver } = action.registrationData;
        
        // Split name into first and last
        const nameParts = name.split(' ');
        const firstName = nameParts[0] || 'Unknown';
        const lastName = nameParts.slice(1).join(' ') || 'Unknown';
        
        // Calculate birthdate from age
        const currentYear = new Date().getFullYear();
        const birthYear = currentYear - age;
        const birthdate = `${birthYear}-06-15`; // Use June 15 as default
        
        // For demo, use a test parent ID - in production this should come from auth
        const parentId = req.auth?.userId || 'demo-parent-123';
        
        const childData = {
          firstName,
          lastName,
          birthdate,
          gradeLevel: grade,
          parentId,
          interests: ['General Learning'],
          learningStyle: 'Visual',
          specialNeeds: medical === 'None' ? null : medical,
          medicalInfo: medical,
          emergencyContacts: [
            {
              name: emergency1 || 'Emergency Contact',
              phone: phone || '',
              relationship: 'Parent/Guardian'
            }
          ]
        };
        
        const child = await storage.createChild(childData);
        console.log('✅ Child registered:', child);
      }
      break;
      
    default:
      console.log('ℹ️ No action execution needed for type:', action.type);
  }
}

/**
 * Parse potential actions from the AI response
 */
function parseActionFromResponse(response: string): any {
  // This function is kept for compatibility but the main logic is now in the service
  return null;
}