/**
 * Stability AI Image Generation Service
 * Alternative to DALL-E for professional coloring page generation
 */

import sharp from 'sharp';
import * as fs from 'fs/promises';
import * as path from 'path';

export async function generateStabilityColoringPage(
  subject: string,
  elements: string[],
  ageRange: string
): Promise<string> {
  console.log(`🎨 Generating coloring page with Stability AI: ${subject} for ages ${ageRange}`);

  try {
    const prompt = createStabilityPrompt(subject, elements, ageRange);
    
    const response = await fetch('https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.STABILITY_API_KEY}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        text_prompts: [
          {
            text: prompt,
            weight: 1
          },
          {
            text: 'blurry, low quality, photorealistic, photograph, 3d render, realistic lighting, shadows, gradients, color, filled shapes',
            weight: -1
          }
        ],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        steps: 30,
        samples: 1,
        style_preset: 'line-art'
      })
    });

    if (!response.ok) {
      throw new Error(`Stability AI API error: ${response.status} ${response.statusText}`);
    }

    const responseData = await response.json();
    
    if (!responseData.artifacts || responseData.artifacts.length === 0) {
      throw new Error('No images generated by Stability AI');
    }

    const imageBase64 = responseData.artifacts[0].base64;
    const imageBuffer = Buffer.from(imageBase64, 'base64');

    // Convert to coloring page format with proper black lines on white background
    const coloringPageBuffer = await convertToColoringPage(imageBuffer, ageRange);
    
    // Create SVG wrapper with embedded PNG for proper display
    const base64Image = coloringPageBuffer.toString('base64');
    const svgContent = `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <!-- Professional ${subject} coloring page for ages ${ageRange} -->
  <rect width="1024" height="1024" fill="white"/>
  <image href="data:image/png;base64,${base64Image}" 
         x="0" y="0" 
         width="1024" height="1024"/>
</svg>`;
    
    console.log(`✅ Generated Stability AI coloring page (${svgContent.length} characters)`);
    return svgContent;

  } catch (error) {
    console.error('❌ Stability AI coloring page generation failed:', error);
    throw error;
  }
}

function createStabilityPrompt(subject: string, elements: string[], ageRange: string): string {
  const [minAge] = ageRange.split('-').map(Number);
  const complexity = minAge <= 5 ? 'very simple' : minAge <= 8 ? 'simple' : 'moderately simple';
  
  return `Simple coloring book page featuring ${subject} with ${elements.join(', ')}. Single bold black outlines only, clean thick lines, no fills or colors. ${complexity} illustration with minimal background detail. Large clear shapes perfect for children ages ${ageRange}. Pure black lines on white background, no double lines, no textures, no detailed patterns. No grass texture, no background clutter. Clean simple outlines ideal for coloring with crayons. Traditional children's coloring book with single bold borders only.`;
}

async function convertToColoringPage(imageBuffer: Buffer, ageRange: string): Promise<Buffer> {
  const [minAge] = ageRange.split('-').map(Number);
  
  // CRITICAL: Process for traditional coloring book with BLACK lines on WHITE background
  const processedImage = await sharp(imageBuffer)
    .grayscale()
    .normalize()
    // Enhance brightness to make background lighter
    .modulate({ 
      brightness: 1.5,
      saturation: 0
    })
    // Edge detection to find outlines
    .convolve({
      width: 3,
      height: 3,
      kernel: [-1, -1, -1, -1, 8, -1, -1, -1, -1]
    })
    // INVERT the image so that dark edges become light and light areas become dark
    .negate()
    // Apply threshold to create binary image - light areas (255) become white, dark areas (0) become black
    .threshold(180)
    // INVERT AGAIN to get final result: black lines on white background
    .negate()
    // Clean up noise
    .median(2)
    .png()
    .toBuffer();

  return processedImage;
}

async function convertToSVG(imageBuffer: Buffer, subject: string, ageRange: string): Promise<string> {
  const base64Image = imageBuffer.toString('base64');
  
  return `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <!-- Professional ${subject} coloring page for ages ${ageRange} -->
  <rect width="1024" height="1024" fill="white"/>
  <image href="data:image/png;base64,${base64Image}" 
         x="0" y="0" 
         width="1024" height="1024" 
         style="mix-blend-mode: multiply;"/>
  
  <metadata>
    <title>${subject} - Professional Coloring Page</title>
    <description>AI-generated educational coloring page featuring ${subject}, suitable for children ages ${ageRange}</description>
    <generator>Stability AI + Edge Detection Processing</generator>
  </metadata>
</svg>`;
}