/**
 * Stability AI Image Generation Service
 * Alternative to DALL-E for professional coloring page generation
 */

import sharp from 'sharp';
import * as fs from 'fs/promises';
import * as path from 'path';

export async function generateStabilityColoringPage(
  subject: string,
  elements: string[],
  ageRange: string
): Promise<string> {
  console.log(`🎨 Generating coloring page with Stability AI: ${subject} for ages ${ageRange}`);

  try {
    const prompt = createStabilityPrompt(subject, elements, ageRange);
    
    const response = await fetch('https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.STABILITY_API_KEY}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        text_prompts: [
          {
            text: prompt,
            weight: 1
          },
          {
            text: 'blurry, low quality, photorealistic, photograph, 3d render, realistic lighting, shadows, gradients, color, filled shapes',
            weight: -1
          }
        ],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        steps: 30,
        samples: 1,
        style_preset: 'line-art'
      })
    });

    if (!response.ok) {
      throw new Error(`Stability AI API error: ${response.status} ${response.statusText}`);
    }

    const responseData = await response.json();
    
    if (!responseData.artifacts || responseData.artifacts.length === 0) {
      throw new Error('No images generated by Stability AI');
    }

    const imageBase64 = responseData.artifacts[0].base64;
    const imageBuffer = Buffer.from(imageBase64, 'base64');

    // Convert to coloring page format
    const coloringPageBuffer = await convertToColoringPage(imageBuffer, ageRange);
    
    // Convert to SVG with embedded image
    const svgContent = await convertToSVG(coloringPageBuffer, subject, ageRange);

    console.log(`✅ Generated Stability AI coloring page (${svgContent.length} characters)`);
    return svgContent;

  } catch (error) {
    console.error('❌ Stability AI coloring page generation failed:', error);
    throw error;
  }
}

function createStabilityPrompt(subject: string, elements: string[], ageRange: string): string {
  const [minAge] = ageRange.split('-').map(Number);
  const complexity = minAge <= 5 ? 'simple and clear' : minAge <= 8 ? 'moderately detailed' : 'detailed';
  
  return `Traditional coloring book page featuring ${subject} with ${elements.join(', ')}. Clean bold black outlines only, thick 3-4 pixel line art, no fills or colors. Professional coloring book style with solid continuous lines perfect for children ages ${ageRange}. ${complexity} educational illustration. Pure black lines on white background, no sketchy or thin lines. Bold closed shapes ideal for coloring with crayons. Traditional children's coloring book quality with thick clean borders.`;
}

async function convertToColoringPage(imageBuffer: Buffer, ageRange: string): Promise<Buffer> {
  const [minAge] = ageRange.split('-').map(Number);
  
  // Enhanced processing for thick coloring book lines
  const processedImage = await sharp(imageBuffer)
    .grayscale()
    .normalize()
    .modulate({ 
      brightness: 1.4,
      saturation: 0
    })
    // Apply stronger edge detection for thicker lines
    .convolve({
      width: 5,
      height: 5,
      kernel: [
        -1, -1, -1, -1, -1,
        -1, -2, -2, -2, -1,
        -1, -2, 16, -2, -1,
        -1, -2, -2, -2, -1,
        -1, -1, -1, -1, -1
      ]
    })
    .threshold(180)
    .negate()
    // Dilate to thicken lines
    .convolve({
      width: 3,
      height: 3,
      kernel: [1, 1, 1, 1, 1, 1, 1, 1, 1]
    })
    .threshold(200)
    // Clean up with morphological closing
    .convolve({
      width: 3,
      height: 3,
      kernel: [0, 1, 0, 1, 1, 1, 0, 1, 0]
    })
    .threshold(150)
    .png()
    .toBuffer();

  return processedImage;
}

async function convertToSVG(imageBuffer: Buffer, subject: string, ageRange: string): Promise<string> {
  const base64Image = imageBuffer.toString('base64');
  
  return `<svg viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <!-- Professional ${subject} coloring page for ages ${ageRange} -->
  <rect width="1024" height="1024" fill="white"/>
  <image href="data:image/png;base64,${base64Image}" 
         x="0" y="0" 
         width="1024" height="1024" 
         style="mix-blend-mode: multiply;"/>
  
  <metadata>
    <title>${subject} - Professional Coloring Page</title>
    <description>AI-generated educational coloring page featuring ${subject}, suitable for children ages ${ageRange}</description>
    <generator>Stability AI + Edge Detection Processing</generator>
  </metadata>
</svg>`;
}